# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cff513d477de2841fac280e4d194d0e15391c2bf894788c185265fda98114e60f236cee964685a25e3300a8ff480cc1813c1733b158b77af598bdf1a751e9d9

test:
  secret_key_base: be6ea8692d030eb1bb07353728d18f79b131e59f480a05aa9cc1b82dd1b170e0f22a3887c2d871c0cb7ecd7822bfe217f87425f7042ea516c295ad736f49219f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
